name: Laravel CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-php@v1
        with:
          php-version: '8.0'
      - run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - run: vendor/bin/phpunit
      - run: zip -r my-laravel-package.zip .
      - uses: actions/upload-artifact@v2
        with:
          name: my-laravel-package
          path: my-laravel-package.zip